import time
import os
import sys
import glob
import json
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, rand
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression
from pyspark.sql.types import StructType, StructField, DoubleType

# Force PySpark to use the exact same Python executable as the current environment
os.environ["PYSPARK_PYTHON"] = sys.executable
os.environ["PYSPARK_DRIVER_PYTHON"] = sys.executable

# 1. Initialize Spark Session
spark = SparkSession.builder \
    .appName("Equipe6_Predicao_TempoReal") \
    .getOrCreate()

# Reduce terminal log output verbosity
spark.sparkContext.setLogLevel("ERROR")

# 2. Train Predictive Model (Historical Synthetic Data)
data = spark.range(0, 1000).select(
    (col("id") * 0.1).alias("horas_operacao"),
    (50 + rand() * 40).alias("temperatura"),
    (35 + rand() * 45).alias("umidade"),
    (0.5 + rand() * 2.5).alias("vibracao")
)
df_sensores = data.withColumn(
    "desgaste_equipamento",
    (col("horas_operacao") * 0.4) + (col("temperatura") * 0.25) + (col("umidade") * 0.08) + (col("vibracao") * 1.8) + (rand() * 2)
)

assembler = VectorAssembler(
    inputCols=["horas_operacao", "temperatura", "umidade", "vibracao"],
    outputCol="features"
)
df_preparado = assembler.transform(df_sensores)

lr = LinearRegression(featuresCol="features", labelCol="desgaste_equipamento")
modelo_lr = lr.fit(df_preparado)

print("\n" + "="*65)
print("=== MODELO TREINADO COM SUCESSO! AGUARDANDO DADOS DO WOKWI... ===")
print("="*65 + "\n")

# 3. Define schema for incoming streaming data
schema = StructType([
    StructField("timestamp", DoubleType(), True),
    StructField("horas_operacao", DoubleType(), True),
    StructField("temperatura", DoubleType(), True),
    StructField("umidade", DoubleType(), True),
    StructField("vibracao", DoubleType(), True)
])

os.makedirs("predictions", exist_ok=True)
prediction_file = "predictions/predictions.csv"

if not os.path.exists(prediction_file):
    with open(prediction_file, "w") as f:
        f.write("timestamp,horas_operacao,temperatura,umidade,vibracao,predicao_desgaste,status\n")

def valid_data(data):
    fields_needed = ["horas_operacao", "temperatura", "umidade", "vibracao"]
    if any(data.get(field) is None for field in fields_needed):
        return False

    return (
        0 <= data["horas_operacao"] <= 100 and
        0 <= data["temperatura"] <= 80 and
        0 <= data["umidade"] <= 100 and
        0 <= data["vibracao"] <= 5
    )

def status_classification(prediction):
    if prediction < 40:
        return "Normal"
    if prediction < 70:
        return "Atencao"
    return "Critico"

processed_archive = None

# 4. In-Memory Reading Loop (Bypasses Hadoop/Windows disk reader limitations)
while True:
    try:
        # Find all JSON files generated by the MQTT bridge
        json_files = glob.glob("stream_data/*.json")
        
        if json_files:
            # Get the most recent JSON file
            latest_file = max(json_files, key=os.path.getmtime)

            if latest_file == processed_archive:
                time.sleep(3)
                continue

            processed_archive = latest_file
            
            with open(latest_file, "r") as f:
                json_data = json.load(f)

            if not valid_data(json_data):
                print(f"[DADO INVALIDO] Arquivo ignorado: {latest_file} -> {json_data}")
                time.sleep(3)
                continue
            
            # Create Spark DataFrame directly in memory from dictionary
            df_stream = spark.createDataFrame([json_data], schema=schema)
            
            # Apply Machine Learning model transformation
            df_features = assembler.transform(df_stream)
            predictions = modelo_lr.transform(df_features)
            
            # Extract and display prediction results
            row = predictions.select("timestamp", "horas_operacao", "temperatura", "umidade", "vibracao", "prediction").first()
            if row:
                status = status_classification(row["prediction"])

                with open(prediction_file, "a") as f:
                    f.write(f"{row['timestamp']},{row['horas_operacao']:.2f},{row['temperatura']:.2f},{row['umidade']:.2f},{row['vibracao']:.2f},{row['prediction']:.2f},{status}\n")

                print(f"⚡ [PREDIÇÃO ML] Horas: {row['horas_operacao']:.1f}h | Temp: {row['temperatura']:.1f}°C | Umidade: {row['umidade']:.1f}% | Vibração: {row['vibracao']:.2f} -> Desgaste Preditivo: {row['prediction']:.2f}% | Status: {status}")

    except Exception as e:
        pass

    time.sleep(3)  # Poll for new predictions every 3 seconds